version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: covid_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagit:
    image: elementl/dagster:1.8.5
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    command: dagit -h 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    volumes:
      - ./dagster:/opt/dagster/dagster_home
    depends_on:
      - run_coordinator

  run_coordinator:
    image: elementl/dagster:1.8.5
    environment:
      DAGSTER_HOME: /opt/dagster/dagster_home
    command: dagster-daemon run
    volumes:
      - ./dagster:/opt/dagster/dagster_home
    depends_on:
      - postgres

volumes:
  postgres_data:
